
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFileChooser;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author André Da Silva
 */
public class SnowFlakeFrame extends javax.swing.JFrame implements SnowFlakePanelListener {

    
    public SnowFlakeFrame() {
        super("SnowFlake Generator");
        initComponents();
        this.setSize(1024,768);
        this.setMinimumSize(new Dimension(1024,768));
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.snowFlakePanel.addSnowFlakePanelListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        marginPanel = new javax.swing.JPanel();
        previewPanel1 = new PreviewPanel();
        previewLabel = new javax.swing.JLabel();
        snowFlakePanel = new SnowFlakePanel();
        ButtonsPanel = new javax.swing.JPanel();
        SalvaPuntiButton = new javax.swing.JButton();
        ImportaPuntiButton = new javax.swing.JButton();
        GeneraButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        salvaPNGButton = new javax.swing.JButton();
        salvaSVGButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        marginPanel.setBackground(new java.awt.Color(255, 255, 255));
        marginPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        marginPanel.setPreferredSize(new java.awt.Dimension(150, 737));

        javax.swing.GroupLayout previewPanel1Layout = new javax.swing.GroupLayout(previewPanel1);
        previewPanel1.setLayout(previewPanel1Layout);
        previewPanel1Layout.setHorizontalGroup(
            previewPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );
        previewPanel1Layout.setVerticalGroup(
            previewPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
        );

        previewLabel.setText("Preview:");

        javax.swing.GroupLayout marginPanelLayout = new javax.swing.GroupLayout(marginPanel);
        marginPanel.setLayout(marginPanelLayout);
        marginPanelLayout.setHorizontalGroup(
            marginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(marginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(previewPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(marginPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(previewLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        marginPanelLayout.setVerticalGroup(
            marginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marginPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(previewLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(previewPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(554, Short.MAX_VALUE))
        );

        getContentPane().add(marginPanel, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout snowFlakePanelLayout = new javax.swing.GroupLayout(snowFlakePanel);
        snowFlakePanel.setLayout(snowFlakePanelLayout);
        snowFlakePanelLayout.setHorizontalGroup(
            snowFlakePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 876, Short.MAX_VALUE)
        );
        snowFlakePanelLayout.setVerticalGroup(
            snowFlakePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 737, Short.MAX_VALUE)
        );

        getContentPane().add(snowFlakePanel, java.awt.BorderLayout.CENTER);

        ButtonsPanel.setBackground(new java.awt.Color(0, 153, 255));

        SalvaPuntiButton.setText("Salva Punti");
        SalvaPuntiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvaPuntiButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(SalvaPuntiButton);

        ImportaPuntiButton.setText("Importa punti");
        ImportaPuntiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportaPuntiButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(ImportaPuntiButton);

        GeneraButton.setBackground(new java.awt.Color(255, 255, 255));
        GeneraButton.setText("Genera");
        GeneraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneraButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(GeneraButton);

        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(ResetButton);

        salvaPNGButton.setText("Salva (PNG)");
        salvaPNGButton.setEnabled(false);
        salvaPNGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvaPNGButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(salvaPNGButton);

        salvaSVGButton.setText("Salva (SVG)");
        salvaSVGButton.setEnabled(false);
        salvaSVGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvaSVGButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(salvaSVGButton);

        getContentPane().add(ButtonsPanel, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GeneraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneraButtonActionPerformed
       this.snowFlakePanel.genSnowFlake();
       this.salvaPNGButton.setEnabled(true);
       this.salvaSVGButton.setEnabled(true);
       this.previewPanel1.setVisible(false);
       this.previewPanel1.SnowFlakeCreated(true);
    }//GEN-LAST:event_GeneraButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        this.snowFlakePanel.pointReset();
        this.salvaPNGButton.setEnabled(false);
        this.salvaSVGButton.setEnabled(false);
        this.previewPanel1.resetCropPolygons();
        this.previewPanel1.SnowFlakeCreated(false);
        this.previewPanel1.setVisible(true);
        this.previewPanel1.repaint();
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void SalvaPuntiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvaPuntiButtonActionPerformed
       
        JFileChooser fileChooser = new JFileChooser();
        
        fileChooser.setDialogTitle("Specify a file to save");   

        int userSelection = fileChooser.showSaveDialog(this);
        
        if (userSelection == JFileChooser.APPROVE_OPTION) {
                         
            File fileToSave = fileChooser.getSelectedFile();  //File da salvare
            try {
                fileToSave = this.snowFlakePanel.writePoints(fileToSave);
            } catch (IOException ex) {
                Logger.getLogger(SnowFlakeFrame.class.getName()).log(Level.SEVERE, null, ex);
            }     
        }
    }//GEN-LAST:event_SalvaPuntiButtonActionPerformed

    private void salvaSVGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvaSVGButtonActionPerformed
       
        JFileChooser fileChooser = new JFileChooser();      
        int userSelection = fileChooser.showSaveDialog(this);
        
        if (userSelection == JFileChooser.APPROVE_OPTION) {
                         
            File fileToSave = fileChooser.getSelectedFile();  //File da salvare
            try {
                fileToSave = this.snowFlakePanel.saveSnowFlake("svg",fileToSave.getAbsolutePath());
            } catch (Exception ex) {
                Logger.getLogger(SnowFlakeFrame.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }
        
    }//GEN-LAST:event_salvaSVGButtonActionPerformed

    private void ImportaPuntiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportaPuntiButtonActionPerformed
        
        JFileChooser chooser = new JFileChooser(); 
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            
            File fileToRead = chooser.getSelectedFile();
            try {
                this.snowFlakePanel.readPoints(fileToRead);
            } catch (IOException ex) {
                Logger.getLogger(SnowFlakeFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ImportaPuntiButtonActionPerformed

    private void salvaPNGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvaPNGButtonActionPerformed

        JFileChooser fileChooser = new JFileChooser();      
        int userSelection = fileChooser.showSaveDialog(this);
        
        if (userSelection == JFileChooser.APPROVE_OPTION) {
                         
            File fileToSave = fileChooser.getSelectedFile();  //File da salvare
            try {
                fileToSave = this.snowFlakePanel.saveSnowFlake("png",fileToSave.getAbsolutePath());
            } catch (Exception ex) {
                Logger.getLogger(SnowFlakeFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println("Save as file: " + fileToSave.getAbsolutePath());            
        }
    }//GEN-LAST:event_salvaPNGButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    //javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SnowFlakeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SnowFlakeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SnowFlakeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SnowFlakeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SnowFlakeFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonsPanel;
    private javax.swing.JButton GeneraButton;
    private javax.swing.JButton ImportaPuntiButton;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton SalvaPuntiButton;
    private javax.swing.JPanel marginPanel;
    private javax.swing.JLabel previewLabel;
    private PreviewPanel previewPanel1;
    private javax.swing.JButton salvaPNGButton;
    private javax.swing.JButton salvaSVGButton;
    private SnowFlakePanel snowFlakePanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void polygonCreated(List<CropPolygon> cp) {
        this.previewPanel1.setCropPolygon(cp);
    }
}
