
import java.awt.Dimension;
import java.io.BufferedWriter;
import javax.swing.JFileChooser;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author André Da Silva
 */
public class SnowFlakeFrame extends javax.swing.JFrame {

    /**
     * Creates new form SnowFlakeFrame
     */
    public SnowFlakeFrame() {
        super("SnowFlake Generator");
        initComponents();
        this.setSize(1024,768);
        this.setMinimumSize(new Dimension(1024,768));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        snowFlakePanel = new SnowFlakePanel();
        ButtonsPanel = new javax.swing.JPanel();
        SalvaPuntiButton = new javax.swing.JButton();
        ImportaPuntiButton = new javax.swing.JButton();
        GeneraButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        salvaPNGButton = new javax.swing.JButton();
        salvaSVGButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout snowFlakePanelLayout = new javax.swing.GroupLayout(snowFlakePanel);
        snowFlakePanel.setLayout(snowFlakePanelLayout);
        snowFlakePanelLayout.setHorizontalGroup(
            snowFlakePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        snowFlakePanelLayout.setVerticalGroup(
            snowFlakePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
        );

        ButtonsPanel.setBackground(new java.awt.Color(0, 153, 255));

        SalvaPuntiButton.setText("Salva Punti");
        SalvaPuntiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvaPuntiButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(SalvaPuntiButton);

        ImportaPuntiButton.setText("Importa punti");
        ImportaPuntiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportaPuntiButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(ImportaPuntiButton);

        GeneraButton.setBackground(new java.awt.Color(255, 255, 255));
        GeneraButton.setText("Genera");
        GeneraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneraButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(GeneraButton);

        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(ResetButton);

        salvaPNGButton.setText("Salva (PNG)");
        salvaPNGButton.setEnabled(false);
        salvaPNGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvaPNGButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(salvaPNGButton);

        salvaSVGButton.setText("Salva (SVG)");
        salvaSVGButton.setEnabled(false);
        salvaSVGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvaSVGButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(salvaSVGButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(snowFlakePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1004, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(snowFlakePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GeneraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneraButtonActionPerformed
       this.snowFlakePanel.genSnowFlake();
       this.salvaPNGButton.setEnabled(true);
       this.salvaSVGButton.setEnabled(true);
    }//GEN-LAST:event_GeneraButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        this.snowFlakePanel.pointReset();
        this.salvaPNGButton.setEnabled(false);
        this.salvaSVGButton.setEnabled(false);
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void SalvaPuntiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvaPuntiButtonActionPerformed
       
        JFileChooser fileChooser = new JFileChooser();
        
        fileChooser.setDialogTitle("Specify a file to save");   

        int userSelection = fileChooser.showSaveDialog(this);
        
        if (userSelection == JFileChooser.APPROVE_OPTION) {
                         
            File fileToSave = fileChooser.getSelectedFile();  //File da salvare
            try {
                fileToSave = this.snowFlakePanel.writePoints(fileToSave);
            } catch (IOException ex) {
                Logger.getLogger(SnowFlakeFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println("Save as file: " + fileToSave.getAbsolutePath());
                  
        }
    }//GEN-LAST:event_SalvaPuntiButtonActionPerformed

    private void salvaSVGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvaSVGButtonActionPerformed
        //this.snowFlakePanel.saveSnowFlake("svg");
    }//GEN-LAST:event_salvaSVGButtonActionPerformed

    private void ImportaPuntiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportaPuntiButtonActionPerformed
        
        JFileChooser chooser = new JFileChooser(); 
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            
            File fileToRead = chooser.getSelectedFile();
            try {
                this.snowFlakePanel.readPoints(fileToRead);
            } catch (IOException ex) {
                Logger.getLogger(SnowFlakeFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ImportaPuntiButtonActionPerformed

    private void salvaPNGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvaPNGButtonActionPerformed

        JFileChooser fileChooser = new JFileChooser();      
        FileNameExtensionFilter filter = new FileNameExtensionFilter("PNG files (.png)", "png");
        fileChooser.setFileFilter(filter);
        int userSelection = fileChooser.showSaveDialog(this);
        
        if (userSelection == JFileChooser.APPROVE_OPTION) {
                         
            File fileToSave = fileChooser.getSelectedFile();  //File da salvare
            fileToSave = this.snowFlakePanel.saveSnowFlake("png",fileToSave.getAbsolutePath());
            System.out.println("Save as file: " + fileToSave.getAbsolutePath());
            
        }
    }//GEN-LAST:event_salvaPNGButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    //javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SnowFlakeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SnowFlakeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SnowFlakeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SnowFlakeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SnowFlakeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonsPanel;
    private javax.swing.JButton GeneraButton;
    private javax.swing.JButton ImportaPuntiButton;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton SalvaPuntiButton;
    private javax.swing.JButton salvaPNGButton;
    private javax.swing.JButton salvaSVGButton;
    private SnowFlakePanel snowFlakePanel;
    // End of variables declaration//GEN-END:variables
}
